# [bell]
# animation = "EaseOutExpo"
# color = "#7d7d7d"
# duration = 150

[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#70c0b1"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#eaeaea"
yellow = "#e7c547"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#864343"
white = "#828482"
yellow = "#9e824c"

[colors.footer_bar]
background = "#c5c8c6"
foreground = "#1d1f21"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.search.focused_match]
background = "#000000"
foreground = "#ffffff"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
# family = "Hack Nerd Font Mono"
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.bold_italic]
# family = "Hack Nerd Font Mono"
family = "Iosevka Nerd Font Mono"
style = "Bold Italic"

[font.italic]
# family = "Hack Nerd Font Mono"
family = "Iosevka Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "Hack Nerd Font Mono"
family = "Iosevka Nerd Font Mono"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:|www.)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

## Control + Backspace for delete a word
[[keyboard.bindings]]
key = "Backspace"
mods = "Control"
chars = "\u0017"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "NONE"

[mouse]
hide_when_typing = false

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_title = true
opacity = 0.95
title = "Alacritty"

[window.dimensions]
columns = 145
lines = 42
